name: 'Reusable Sync'

on:
  workflow_call:

jobs:
  gitee:
    name: Sync to Gitee

    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Sync
        uses: ttionya/Repository-Sync-Hub@v1
        with:
          target_repository: 'https://gitee.com/ttionya/picgo-plugin-lychee.git'
          http_access_name: 'ttionya'
          http_access_token: ${{ secrets.GITEE_HTTP_ACCESS_TOKEN }}
